spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=AwardNominationDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=LOWAga20
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.application.name=awardnomination